# Workin in progress
version: '3.9'

services:
    vtn-fast-api:
        container_name: vtn
        hostname: vtn
        build:
            context: .
        ports:
            - "8000:8000" # FastAPI
            - "8080:8080" # VTN Server
        environment:
            - ./.env
        networks:
            - openadr-net

networks:
    openadr-net:
        driver: bridge
